# Generated by Django 3.0.6 on 2020-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desfibrilador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('localización', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
    ]
