# Generated by Django 3.0.6 on 2020-05-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desfibrilador',
            old_name='localización',
            new_name='localizacion',
        ),
    ]
