# Generated by Django 3.0.6 on 2020-05-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_transmision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=100)),
                ('rev_type', models.CharField(max_length=20)),
                ('rev_date', models.DateTimeField(verbose_name='date revision')),
                ('desfibrilador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Desfibrilador')),
            ],
        ),
    ]
