# Generated by Django 3.0.6 on 2020-05-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Desfibrilador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_desfibrilador', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_revision', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='rev_type',
            new_name='rev_tipo',
        ),
    ]
