# Generated by Django 3.0.6 on 2020-05-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20200507_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desfibrilador',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.Tipo_Desfibrilador'),
        ),
    ]
