# Generated by Django 3.0.6 on 2020-05-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20200507_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='rev_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.Tipo_Revision'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='tecnico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='control.Tecnico'),
        ),
    ]
