# Generated by Django 3.0.6 on 2020-05-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20200507_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control.Tecnico'),
        ),
    ]
