# Generated by Django 3.0.6 on 2020-05-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20200507_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='desfibrilador',
            name='imagen',
            field=models.ImageField(default='pic.png', upload_to='images/'),
        ),
    ]
